name: Docker Image CI
on:
  push:
    branches: [ "staging" ]
    paths:
      - '*Dockerfile'
  pull_request:
    branches: [ "main" ]
    paths:
      - '*Dockerfile'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag flask_app:$(date +%s)
